Models/ErrorViewModel.cs
namespace Assignment8.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment8.Models{
    public class Student{
        [Key]
        public int StudentId{get; set;}

        [Required]
        public string Name{get; set;}

        [Required]
        public string Class{get; set;}

        // [ForeignKey("Subject")]
        // [Display(Name="Subject")]

        // public int SubjectId {get; set;}

        // public virtual Subject Subject {get; set;}
    }
}

Models/Subject.cs
using System.ComponentModel.DataAnnotations;

namespace Assignment8.Models{

 public class Subject
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string Subject_Name { get; set; }

        public string syllabus { get; set; }

        [Range(1,5)]
        public int credits { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Assignment8.Models;

namespace Assignment8.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }


  
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/StudentController.cs
using Assignment8;
using Assignment8.Models;
using Assignment8.data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace Assignment8.Controllers
{
        public class StudentController : Controller
    {

        public readonly ApplicationDbContext _db;

        public StudentController(ApplicationDbContext db)
        {
            _db = db;
        }

        private void PopulateSubjectsDropDownList (object selectedSubject = null )
        {
            var subjectsQuery = from s in _db.Subject
                                orderby s.Subject_Name
                                select new {SubjectId = s.ID, s.Subject_Name};

           ViewBag.SubjectID = new SelectList(subjectsQuery.AsNoTracking(),"SubjectId","Subject_Name",selectedSubject);

        }

        public IActionResult Index(string searchString)
        {

            IEnumerable<Student> objList = _db.Student;

            if(!String.IsNullOrEmpty(searchString))
            {
                objList = objList.Where(s => s.Name.Contains(searchString));
            }
            return View(objList);
        }

        //Get Create
        public IActionResult Create()
        {
            PopulateSubjectsDropDownList(); 
            return View();
        }


        [HttpPost]
        public IActionResult Create([Bind("Name,Class,SubjectId")] Student studobj)
        {
            if (ModelState.IsValid)
            {
                _db.Student.Add(studobj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(studobj);
        }

        //Get Create
        public IActionResult Edit(int id)
        {
            
           var  studobj = _db.Student.Find(id);
            return View(studobj);
        }


        [HttpPost]
        public IActionResult Edit(Student obj)
        {
            if (ModelState.IsValid)
            {
                _db.Student.Update(obj);
                _db.SaveChanges();
               return  RedirectToAction("Index");
            }
             return View(obj); 
        }

        //Get Delete
        public IActionResult Delete(int id)
        {

            var studobj = _db.Student.Find(id);
            return View(studobj);
        }


        [HttpPost]
        public IActionResult DeletePost(int studentid)
        {
            var studobj = _db.Student.Find(studentid);

            if (ModelState.IsValid)
            {

                _db.Student.Remove(studobj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(studobj);
        }
    }
}

Controllers/SubjectController.cs
using Assignment8;
using Assignment8.Models;
using Assignment8.data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment8.Controllers
{
    public class SubjectController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SubjectController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index(string searchString)
        {

            IEnumerable<Subject> objList = _db.Subject;

            if(!String.IsNullOrEmpty(searchString))
            {
                objList = objList.Where(s => s.Subject_Name.Contains(searchString));
            }
            return View(objList);
        }

        [HttpGet]
        public IActionResult Edit(int subjectid)
        {
            var subobj = _db.Subject.Find(subjectid);
            return View(subobj);

        }

        [HttpPost]
        public IActionResult Edit(Subject updatedvaluesobj)
        {
            _db.Subject.Update(updatedvaluesobj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
        
        [HttpGet]
       public IActionResult Create()
        {
           
            return View();
        }


        [HttpPost]
        public IActionResult Create(Subject subobj)
        {
            if (ModelState.IsValid)
            {
                _db.Subject.Add(subobj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(subobj);
        }

        public IActionResult Delete(int subjectid)
        {
            var subobj =  _db.Subject.Find(subjectid);
            return View(subobj);
        }
        [HttpPost]
        public IActionResult  DeletePost(int ID)
        {
            var subobj=_db.Subject.Find(ID);
            if(ModelState.IsValid)
            {
                _db.Subject.Remove(subobj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(subobj);
        }
       
        
       
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>To our mvc app.</p>
    <marquee >Hello Guys... </marquee>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment8</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment8.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="myHeader">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a  class=" font-weight-bold navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC CRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="text-white nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>

                        <li class="nav-item">
                            <a class="text-white nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="text-white nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Index">Subject</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div style="color : black" class="container">
            &copy; 2022 - The MSU Student - Teacher Portal - <a asp-area="" asp-controller="Home" style="color : black" asp-action="Student">Student</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Create.cshtml
@model Assignment8.Models.Student

@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-action="Create">
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Student</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Class"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Class" class="form-control" />
                        <span asp-validation-for="Class" class="text-danger"></span>
                    </div>
-
                @* </div>
                  <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Subject" class="control-label"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="SubjectId" class="form-control" asp-items="ViewBag.SubjectId">
                            <option value="">--Select Subject--</option>
                        </select>
                        
                        <span asp-validation-for="SubjectId" class="text-danger"></span>
                    </div> *@

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Student/Delete.cshtml
@model Assignment8.Models.Student

<form method="post" asp-action="DeletePost">
    <input asp-for="StudentId" hidden />
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Student Details</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Class"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Class" disabled class="form-control" />
                        <span asp-validation-for="Class" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Student/Edit.cshtml
@model Assignment8.Models.Student

<form method="post" asp-action="Edit">
    <input asp-for="StudentId" hidden />
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Student Details</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Class"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Class" class="form-control" />
                        <span asp-validation-for="Class" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Student/Index.cshtml
@model IEnumerable<Assignment8.Models.Student>

<div class="container p-3">
    <div class="d-flex justify-content-between">
        <div>
            <h2 class="text-primary text-dark">Student List</h2>
        </div>
        
        <form asp-controller="Student" asp-action="Index">
          <p>
             Student Name : <input placeholder="Search Name" type="text" name="SearchString" />
             <input type="submit" value="Filter">
         </p>
        </form> 
       
    </div>
    
     <a asp-controller="Student" asp-action="Create" class="text-center btn btn-primary col-12">
            Create New Student
        </a>
    </div>
    @if(Model.Count() > 0)
            {
                <table class="table table-bordered table-striped" style="width:100%">
                    <thead>
                        <tr>
                            <th>Student Name</th><th>Class</th><th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var obj1 in Model)
                {
                    <tr><td width="50%">@obj1.Name</td>
                    <td>@obj1.Class</td><td>
    <a class="btn btn-primary" asp-route-id="@obj1.StudentId" asp-controller="Student" asp-action="Edit">Edit</a>
    <a class="btn btn-primary" asp-route-id="@obj1.StudentId" asp-controller="Student" asp-action="Delete">Delete</a>
</td></tr>
                }
                    </tbody>
                </table>
            }
    else
    {
    <p> No student details.</p>
    }
    </div>

Views/Subject/Create.cshtml
@model Assignment8.Models.Subject

@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-action="Create">
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Subject</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Subject_Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Subject_Name" class="form-control" />
                        <span asp-validation-for="Subject_Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="syllabus"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="syllabus" class="form-control" />
                        <span asp-validation-for="syllabus" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="credits"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="credits" class="form-control" />
                        <span asp-validation-for="credits" class="text-danger"></span>
                    </div>
                </div>
        
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Add" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Subject/Delete.cshtml
@model Assignment8.Models.Subject

<form method="post" asp-action="DeletePost">
    <input asp-for="ID" hidden />
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Subject Details</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Subject_Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Subject_Name" disabled class="form-control" />
                        <span asp-validation-for="Subject_Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="syllabus"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="syllabus" disabled class="form-control" />
                        <span asp-validation-for="syllabus" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Subject/Edit.cshtml
@model Assignment8.Models.Subject

<form method="post" asp-action="Edit">
    <input hidden asp-for="ID"/>
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Subject</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Subject_Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Subject_Name" class="form-control" />
                        <span asp-validation-for="Subject_Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="syllabus"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="syllabus"  class="form-control" />
                        <span asp-validation-for="syllabus" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="credits"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="credits" class="form-control" />
                        <span asp-validation-for="credits" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update subject Details" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Subject/Index.cshtml
@model IEnumerable<Assignment8.Models.Subject>


<div class="container p-3">
    <div class="d-flex justify-content-between">
        <div class="col-8">
            <h2 class="text-dark-primary">Subject List</h2>
        </div>
        <form asp-controller="Subject" asp-action="Index">
            
          <p>
             Subject Name : <input placeholder="Search Subject" type="text" name="SearchString" />
             <input type="submit" value="Filter">
         </p>
        </form> 
    </div>
    <a asp-area="" asp-controller="Subject" asp-action="Create" class="text-center btn btn-primary col-12">Create New Subject</a>
    </div>
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Subject Name</th>
                    <th>Syllabus</th>
                    <th>Credits</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj1 in Model)
                {
                    <tr>
                        <td width="50%">@obj1.Subject_Name</td>
                        <td>@obj1.syllabus</td>
                        <td>@obj1.credits</td>
                        <td>
                           <a asp-controller="Subject" asp-action="Edit" asp-route-subjectid="@obj1.ID" class="btn btn-primary">Edit</a>
                            <a asp-controller="Subject" asp-action="Delete" asp-route-subjectid="@obj1.ID" class="btn btn-primary">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> No subject details.</p>
    }
</div>